const types = {
	FETCH_PODCASTS_REQUEST: 'FETCH_PODCASTS_REQUEST',
	FETCH_PODCASTS_SUCCESS: 'FETCH_PODCASTS_SUCCESS',
	FETCH_PODCASTS_ERROR: 'FETCH_PODCASTS_ERROR',
	SET_LIST_FILTER: 'SET_LIST_FILTER'
};

export default types;
