const types = {
	FETCH_PODCASTS_REQUEST: 'FETCH_PODCASTS_REQUEST',
	FETCH_PODCASTS_SUCCESS: 'FETCH_PODCASTS_SUCCESS',
	FETCH_PODCASTS_ERROR: 'FETCH_PODCASTS_ERROR',
	SET_LIST_FILTER: 'SET_LIST_FILTER',

	FETCH_PODCAST_DETAIL_REQUEST: 'FETCH_PODCAST_DETAIL_REQUEST',
	FETCH_PODCAST_DETAIL_SUCCESS: 'FETCH_PODCAST_DETAIL_SUCCESS',
	FETCH_PODCAST_DETAIL_ERROR: 'FETCH_PODCAST_DETAIL_ERROR'

};

export default types;
